### ISSUE TITLE
received fatal signal 11 (segv)

### ISSUE THREAD

**Issue by robertsimione** [SWI-Prolog/swipl-devel#226]
```
~$ echo "
> :- use_module(library(tabling)).
> :- table fib/2.
> :- use_module(library(clpfd)).
> 
> fib(1, 1).
> fib(2, 2).
> fib(N, X) :- N #> 2, N1 #= N-1, N2 #= N-2,
>     fib(N1, X1), fib(N2, X2), X #= X1+X2.
> " > bug.pl
~$ swipl bug.pl
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.32)
Copyright (c) 1990-2016 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- fib(N, 13)?- fib(N, 13).

SWI-Prolog [thread 1 (main) at Sun May  7 17:47:00 2017]: received fatal signal 11 (segv)
C-stack trace labeled "crash":
  [0] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(save_backtrace+0xb5) [0x10e2a3025]
  [1] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(crashHandler+0x9b) [0x10e2a35fb]
  [2] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(dispatch_signal+0x21b) [0x10e241fab]
  [3] /usr/lib/system/libsystem_platform.dylib(_sigtramp+0x1a) [0x7fffe1c95b3a]
  [4] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(createSupervisor+0x755) [0x10e26af15]
  [5] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(pl_tbl_table_discard_all0_va+0x77) [0x10e27a2d7]
  [6] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(PL_next_solution+0x8ba2) [0x10e1d3fa2]
  [7] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(query_loop+0x143) [0x10e222823]
  [8] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(prologToplevel+0x51) [0x10e222e71]
  [9] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(PL_toplevel+0x38) [0x10e1e5258]
  [10] /Applications/SWI-Prolog.app/Contents/MacOS/swipl(main+0x35) [0x10e1baf25]
  [11] /usr/lib/system/libdyld.dylib(start+0x1) [0x7fffe1a86235]
Abort trap: 6
~$ 
```

**Comment by JanWielemaker** [comment]
AFAIK, this is an old bug that is already fixed.  I think in 7.4.2, surely in 7.5.5.  Re-open if not.

**Comment by robertsimione** [comment]
@JanWielemaker I installed 7.5.5 but still get the same thing. (I can not re-open issues closed by a repo maintainer.) Also, this happened on swish.swi-prolog.org . First I'll show my terminal then a link to a relevant swish program:

```
~$ swipl --version
SWI-Prolog version 7.5.5 for x86_64-darwin15.6.0
~$ swipl bug.pl 
Welcome to SWI-Prolog (threaded, 64 bits, version 7.5.5)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

Cannot read termcap database;
using dumb terminal settings.
?- fib(N, 13).

SWI-Prolog [thread 1 (main) at Mon May  8 09:30:16 2017]: received fatal signal 11 (segv)
C-stack trace labeled "crash":
  [0] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(save_backtrace+0xb5) [0x10fc2ba55]
  [1] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(crashHandler+0x9b) [0x10fc2c04b]
  [2] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(dispatch_signal+0x21b) [0x10fbc8c7b]
  [3] /usr/lib/system/libsystem_platform.dylib(_sigtramp+0x1a) [0x7fffe1c95b3a]
  [5] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(pl_tbl_table_discard_all0_va+0x77) [0x10fc01c97]
  [6] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(PL_next_solution+0x8cc8) [0x10fb58c68]
  [7] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(query_loop+0x143) [0x10fba8c73]
  [8] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(prologToplevel+0x51) [0x10fba92d1]
  [9] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(PL_toplevel+0x38) [0x10fb6a398]
  [10] /Applications/SWI-Prolog.app/Contents/MacOS/swipl(main+0x25) [0x10fb42f65]
  [11] /usr/lib/system/libdyld.dylib(start+0x1) [0x7fffe1a86235]
Abort trap: 6
~$ 
```

This issue can also be seen on swish at the following program:

http://swish.swi-prolog.org/p/Something%20bad%20happened....pl

If you query `fib(N, 13).` Then you get an error message:

```
502 Bad Gateway
nginx/1.10.0 (Ubuntu)
```

**Comment by cjfpainter** [comment]
FWIW The tabling doesn't help, take it out and...?- fib(N,13).N = 6 -----Robert Simione <notifications@github.com> wrote: -----To: SWI-Prolog/swipl-devel <swipl-devel@noreply.github.com>From: Robert Simione <notifications@github.com>Date: 05/08/2017 02:35PMCc: Subscribed <subscribed@noreply.github.com>Subject: Re: [SWI-Prolog/swipl-devel] received fatal signal 11 (segv) (#226)@JanWielemaker I installed 7.5.5 but still get the same thing. (I can not re-open issues closed by a repo maintainer.) Also, this happened on swish.swi-prolog.org . First I'll show my terminal then a link to a relevant swish program:
~$ swipl --versionSWI-Prolog version 7.5.5 for x86_64-darwin15.6.0~$ swipl bug.pl Welcome to SWI-Prolog (threaded, 64 bits, version 7.5.5)SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.Please run ?- license. for legal details.For online help and background, visit http://www.swi-prolog.orgFor built-in help, use ?- help(Topic). or ?- apropos(Word).Cannot read termcap database;using dumb terminal settings.?- fib(N, 13).SWI-Prolog [thread 1 (main) at Mon May  8 09:30:16 2017]: received fatal signal 11 (segv)C-stack trace labeled "crash":  [0] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(save_backtrace+0xb5) [0x10fc2ba55]  [1] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(crashHandler+0x9b) [0x10fc2c04b]  [2] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(dispatch_signal+0x21b) [0x10fbc8c7b]  [3] /usr/lib/system/libsystem_platform.dylib(_sigtramp+0x1a) [0x7fffe1c95b3a]  [5] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(pl_tbl_table_discard_all0_va+0x77) [0x10fc01c97]  [6] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(PL_next_solution+0x8cc8) [0x10fb58c68]  [7] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(query_loop+0x143) [0x10fba8c73]  [8] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(prologToplevel+0x51) [0x10fba92d1]  [9] /Applications/SWI-Prolog.app/Contents/swipl/lib/x86_64-darwin15.6.0/libswipl.dylib(PL_toplevel+0x38) [0x10fb6a398]  [10] /Applications/SWI-Prolog.app/Contents/MacOS/swipl(main+0x25) [0x10fb42f65]  [11] /usr/lib/system/libdyld.dylib(start+0x1) [0x7fffe1a86235]Abort trap: 6~$ 
This issue can also be seen on swish at the following program:
http://swish.swi-prolog.org/p/Something%20bad%20happened....pl
If you query fib(N, 13). Then you get an error message:
502 Bad Gatewaynginx/1.10.0 (Ubuntu)

**Comment by JanWielemaker** [comment]
Ok, thanks.  It looked so much like the program and stack of a fixed bug and you reported an old version, so I assumed it  was the same old bug.  Probably the fix is incomplete :(

**Comment by robertsimione** [comment]
@JanWielemaker Thanks for looking into it.

**Comment by JanWielemaker** [comment]
Fixed with b062a3a80f6b38b3addd8971e9d31cfdaa8058ac.  Note that instead of a crash you now get a regular Prolog exception.   That is intended.   This is caused by the fact that tabling this predicate involves tabling goal variants that include clp(fd) constraints.  The notion of variance isn't very well defined in the presence of constraints.  If it was, we also get solutions that contain constraints.  As tabling in the end implies copying terms and copying terms holding constraints is pretty hazardous (search for tabling and findall/3, etc). this is hard to deal with as well.

AFAIK, various articles have been published about combining tabling and constraints.  As is, this is out of scope for SWI-Prolog's rather naive tabling implementation.  It shouldn't crash on a SEGV though.

**Comment by robertsimione** [comment]
Thanks @JanWielemaker
