### ISSUE TITLE
GUI Components All Blank Initially

### ISSUE THREAD

**Issue by epeld** [SWI-Prolog/swipl-devel#228]
Hi I am using SWI-Prolog 7.4.2 (I also tried 6.6.4) and whenever I view something in PCE (e.g the documentation or class browser) I initially see just a blank window. I have to either resize the window or wait approximately 3 seconds for the window contents to show up. It is as if the window 'draw' routine doesn't trigger initially but I can force it to happen manually.

I am using a linux system (Trisquel) if that matters!

**Comment by wouterbeek** [comment]
I have had this issue too (for years) on Fedora and Ubuntu (Gnome 3 desktop environments).

**Comment by JanWielemaker** [comment]
I know it.  It seems to depend on the window manager you use.  Just moving also works.  Should be resolved, but I have little clue why this happens.

**Comment by wouterbeek** [comment]
Do we know somebody who might know?  (An X11 expert maybe.)

**Comment by cjfpainter** [comment]
Hi Guys,FWIW I don't get this effect on X server 11.0/Ubuntu 14.04/SWI 7.5. Good luck, sorry can't be more helpful!-----Wouter Beek <notifications@github.com> wrote: -----To: SWI-Prolog/swipl-devel <swipl-devel@noreply.github.com>From: Wouter Beek <notifications@github.com>Date: 05/14/2017 10:55AMCc: Subscribed <subscribed@noreply.github.com>Subject: Re: [SWI-Prolog/swipl-devel] GUI Components All Blank Initially (#228)Do we know somebody who might know?  (An X11 expert maybe.)

**Comment by epeld** [comment]
I have tried to create a minimum example that reproduces this but strangely all the simple examples I've tried so far work as expected. My idea was to create some components and add contents to them before displaying them. So far I've tried: creating a picture with some boxes, creating a dialog with a button. Will keep looking!

It would be useful if we can find an example application that reproduces this. Then we can reduce the example line by line until we find the cause. Since the built-in IDE-components exhibit this, but my test apps don't I feel fairly certain we should be able to find the issue using this strategy.

**Comment by JanWielemaker** [comment]
If I recall well, the issue is related to the class `persistent_frame` that saves and reloads the window position and layout.   At some point this waits for an X11 event and that used to get send right away, but sometimes gets delayed in some X11 configurations (I think notably related to the window manager).  I don't really recall what is waiting for which event.  I think it has something to do with either the X11 mapping/reparent event (forgot the detail) or geometry event.   That is as far as I my memory goes.

**Comment by JanWielemaker** [comment]
Closer.  Enable `?- pce_debug(frame).` before `?- manpce.` and you'll see it hang after printing

    @manual/man_manual: doing widget geometry request

That message comes from `src/x11/xframe.c`, function `ws_geometry_frame()`.  Opening `manpce` leads to 3 geometry requests, while similar calls that work just fine only have one geometry request.

**Comment by JanWielemaker** [comment]
A bit of puzzling makes the conditions more clear.  The minimal program seems to be about the program below with two additional remarks:

  - The `geometry` class variable is needed.
  - The problem seems to vanish if you move the window elsewhere, close it and create a new
     one.   Without knowing what is going on, this may be the clue for a work-around: ignore the
     (default and initial) geometry if we need to restore a user geometry.

```
:- use_module(library(pce)).
:- use_module(library(persistent_frame)).

:- pce_global(@t, new(test)).

:- pce_begin_class(test, persistent_frame).

class_variable(geometry,        geometry,               '+0+0').

initialise(F) :->
    send_super(F, initialise, 'Pretty Application'),
    send(F, icon, resource(man_icon)),
    send(F, geometry_key, pretty_app),
    send(F, append, new(D, dialog)),
    send(D, append, button(close, message(F, destroy))),
    send(D, append, button(ok,    message(@display, confirm, ok))),
    send(F, expose).

:- pce_end_class.

t :-
    in_pce_thread(send(@t, expose)).
```

**Comment by epeld** [comment]
Another observation: alt+f4 (i.e closing the window) is also postponed until the first redraw happens.

That is, if I take JanWielemaker's example above and immediately hit alt+f4 when the window opens it will eventually close, but not before waiting approximately 3 seconds. If hit alt+f4 and then force a redraw by moving or resizing the window then it is closed immediately.

**Comment by JanWielemaker** [comment]
That is understandable as it is blocked in the geometry request and thus it isn't processing any events.   At this moment I'm looking into two suspect observations:

  - It computes the window geometry wrong.   The X geometry is defined as the location and size of 
    window including the _decorations_.  However, the window manager adds a drop-shadow (I'm
    using Cinnamon, which uses the Muffin windows manager) and a window place in the top-left corner 
   claimed to be at -8,-9.  That isn't really xpce's fault; `xwininfo` reports the same geometry. I thought 
   negative X,Y, which is anyway ignored by this window manager, was the problem, but
   changing the code never to use negative coordinates doesn't change the behaviour.

 - I'm starting to suspect explicit placement of a window at 0,0 is the problem.

The key seems to be the window manager.  Right now,

  - Cinnamon/Muffin goes wrong.   Has drop-shadow around windows.  It also has _active corners_
    configured.
  - XFCE/xfwm4 works fine.  No drop-shadow and now _active corners_.

**Comment by JanWielemaker** [comment]
It is really waiting for the window manager.  Interrupting during the blank screen gives this stack trace:

```
#0  0x00007ffff759fb5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff526af72 in _XtWaitForSomething ()
   from /usr/lib/x86_64-linux-gnu/libXt.so.6
#2  0x00007ffff5278898 in ?? () from /usr/lib/x86_64-linux-gnu/libXt.so.6
#3  0x00007ffff5262e07 in _XtMakeGeometryRequest ()
   from /usr/lib/x86_64-linux-gnu/libXt.so.6
#4  0x00007ffff5263000 in XtMakeGeometryRequest ()
   from /usr/lib/x86_64-linux-gnu/libXt.so.6
#5  0x00007ffff5c29d50 in ws_geometry_frame (fr=fr@entry=0xa57c48, x=x@entry=0x1, 
```

**Comment by JanWielemaker** [comment]
Hmmm.  Using `XtMakeGeometryRequest` with an X-coordinate of 0 or less seems to trigger this in some situations.  I pushed a patch that ensures the X is at minimum `1`.  That resolves the issue for me.  Please test.

**Comment by epeld** [comment]
Hi!
Unfortunately, the issue remains for me even after your fix.

I cloned the swipl-devel repo and built it from scratch (and I can see your commit in the git log of packages/xpce).

PS. On a side note, the build procedure for XPCE doesn't quite work for me out of the box. On typing `make install` I see this: 
    
    swipl -C "/usr/local/lib/swipl-7.5.6/xpce" -f none -t 'halt(1)' \
			-g "make_library_index('prolog/lib'),halt"

and then I end up in the REPL. Somehow I got it working by typing "halt" manually.

**Comment by epeld** [comment]
Some additional thoughts, FWIW:

Looking through the source code of libXt, they support something called "tattling" which means logging calls for specific Windows/Components. In `Intrinsic.c` they mention how to enable this using a resource database file but I am not sure I understand how to do it yet..

The function mentioned in the stacktrace above, `XtMakeGeometryRequest`, has tons of these log messages and it also returns different statuses (e.g `XtGeometryYes`, `XtGeomtryDone` etc). Maybe these things differ when the process hangs and when it doesn't.

A plausible work around - at least for me - would be to just disable the geometry persistence. Maybe persistent_frame could read some kind of config flag?

**Comment by JanWielemaker** [comment]
> and then I end up in the REPL. Somehow I got it working by typing "halt" manually.

That is rather dubious.  There is some slight possibility you are still using parts of the old system.
You can verify using `?- tracepce(frame->set).` and then `?- manpce.`.   Before, you could see negative X and Y.  With this patch you should see X=1 and Y=0 for opening in the top-left corner.   It is also interesting to see whether you can reproduce my observation that if you move the window elsewhere and close it, reopening works fine.

> A plausible work around - at least for me - would be to just disable the geometry persistence. Maybe persistent_frame could read some kind of config flag?

Such measures are really last resort.  It creates a lot of traffic and confusion.

> Googling XtWaitForSomething hangs

That is to be expected as this call is involved in all X11 interactions that wait for a confirmation from the server.   Basically a geometry request for a toplevel window ends up at the window manager, which does its magic and replies.  Under some conditions, something goes wrong here.  I think the real bug is in the Window manager, but I fear it is too hard to describe the conditions, desired and experienced behaviour to file a proper bug report and it is also unclear where.   It happens in some window managers, but not all.  The fact that it appears in multiple hints at a bug on our side, but possibly the affected code is copied/shared between window managers.

**Comment by epeld** [comment]
Hi Jan,
I ran the commands you suggested and here is the output:

    [4] enter M @manual/man_manual ->set(1, 1, @default/constant, @default/constant, @default/constant)
    [4] exit M @manual/man_manual ->set(1, 1, @default/constant, @default/constant, @default/constant)
    [5] enter M @manual/man_manual ->set(1, 1, @default/constant, @default/constant, @default/constant)
    [5] exit M @manual/man_manual ->set(1, 1, @default/constant, @default/constant, @default/constant)
    [1] enter M @manual/man_manual ->set(1, 1, @default/constant, @default/constant, @default/constant)
    [1] exit M @manual/man_manual ->set(1, 1, @default/constant, @default/constant, @default/constant)

the problem still persists. After having moved the window - as per your suggestion - the problem remains. The output is then:

    [4] enter M @manual/man_manual ->set(1, 1, @default/constant, @default/constant, @default/constant)
    [4] exit M @manual/man_manual ->set(1, 1, @default/constant, @default/constant, @default/constant)
    [5] enter M @manual/man_manual ->set(210, 63, @default/constant, @default/constant, @default/constant)
    [5] exit M @manual/man_manual ->set(210, 63, @default/constant, @default/constant, @default/constant)
    [1] enter M @manual/man_manual ->set(210, 63, @default/constant, @default/constant, @default/constant)
    [1] exit M @manual/man_manual ->set(210, 63, @default/constant, @default/constant, @default/constant)

I did some research about my window manager and I am running metacity 2.34.13 (GNOME 2). You mentioned that you were running Muffin, which appears to be a derivative of Mutter, the GNOME 3 WM. I suppose it is not unthinkable that the two window managers share a common base library which contains the bug. This would also mean that SWI-Prolog needn't be at fault just because there are multiple different WMs invovled :)

After a bit of looking around I found a mention of a similar-sounding bug in the metacity logs: 

    2007-04-11  Elijah Newren  <newren gmail com>

	Make sure apps have correct info about their coordinates, even on
	unmap.  Fixes temporary hang with libXt (XtVaSetValues setting x & y coordinates). #399552.

So now I am looking into building a later version of metacity than my distro supports, just to see if the problem has been fixed.

**Comment by epeld** [comment]
Actually, nevermind about the commit mentioned above. 2.34 was released way later than 2007.

**Comment by epeld** [comment]
Hi, again!
I just wanted to confirm that this is indeed an issue in the window manager.

I switched to openbox as my WM and the GUI displays instantly! This is a good enough "workaround" for me. 

Thanks a lot for helping me out!

**Comment by wouterbeek** [comment]
Is it possible that this issue is now fixed?  I have not seen it using the most recent checkout from the development branch.

**Comment by epeld** [comment]
Well that's fine by me. I found a workaround, thanks to you guys. The problem was still there for me however (I pasted some debug output above).

I guess you could say one bug has been fixed (i.e for modern WMs) but for my (slightly dated) WM there is yet another bug. I don't think many people will notice though, and if they do, there will be workarounds.

You decide.

**Comment by wouterbeek** [comment]
I'm closing this issue now because otherwise it may linger.  If somebody else runs into the outdated WM issue s/he can open a new issue with that specific purpose.

@epeld Thanks for starting the issue in the first place!  The GUI tracer now works better for the majority of users.

**Comment by triska** [comment]
I have the same issue that @epeld mentioned here, during compilation and installation from source: Almost every time, it hangs by entering the toplevel, and I have to exit the toplevel with Ctrl+d or `halt/0` so that compilation continues. Platform is Debian. (In fact, I find the whole compilation procedure quite strange and erratic, since the flags I specify are often not propagated, or only propagated to some parts of the packages, or only if I use the build template which I consider a quite unusual requirement.)

**Comment by triska** [comment]
It is also quite hard to test: For example, suppose I want to start from a clean slate with the packages, so I do a `make distclean` in the "packages" directory. This also removes `configure`. Yet, I cannot easily get just `configure` back: If I run `./configure` in `swipl-devel`, it tells me that everything is up to date and refuses to do anything further. So I have to run `git clean -fx` also in the main repository just so that I can even start to rebuild the packages from scratch? Then there's another `configure` also in the `src` directory etc.

**Comment by wouterbeek** [comment]
@triska Valid points (as always), but these seem to be multiple, related points that somehow interact?  Could you open separate issues for these?  Or otherwise just reopen this issue if you believe this to be the right place.

**Comment by JanWielemaker** [comment]
Copy `build.templ` at the toplevel to `build` and edit it to suit your configuration.  After that, a

    make distclean
    git pull
    ./prepare
    ./build

should get you a nice fresh system.   `make distclean` removes all build products.  The configure files
are also build products.  `./prepare` creates them.   This is totally distinct from the issue at hand in this topic.  That issue is indeed only partly solved.  I has a few issues with the graphical debugger opening with a blank screen today.  This is still a window-manager related problem.  Builds ending up in the toplevel during build is unknown to me.
