### ISSUE TITLE
free(): invalid next size (fast): 0x00000000027612b0

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swipl-devel#246]
To reproduce this issue with the current git version of SWI-Prolog, please perform the following steps:

  1. Download [**bitcoinolog.pl**](https://www.metalevel.at/bitcoinolog/bitcoinolog.pl)
  2. Run the following command:
         `$ swipl -f none bitcoinolog.pl`
  3. Run the following query:

<pre>
   ?- repeat,
          new_private_key(PrivateKey),
          private_key_to_public_key(PrivateKey, PublicKey),
          public_key_to_address(PublicKey, Address),
          portray_clause(Address),
          false.
</pre>

This *generates* dozens of Bitcoin addresses and emits them on standard output. However, within a few seconds, SWI-Prolog **crashes** on my system (Debian) with one of the following error messages:

<pre>
*** Error in `/usr/local/bin/swipl': free(): invalid next size (fast): 0x00000000027612b0 ***
Inconsistency detected by ld.so: dl-fini.c: 205: _dl_fini: Assertion `ns != 0 || i == nloaded' failed!
</pre>

*or*

<pre>
*** Error in `/usr/local/bin/swipl': double free or corruption (!prev): 0x0000000002439c40 ***
</pre>

*or*

<pre>
*** Error in `/usr/local/bin/swipl': free(): invalid next size (fast): 0x0000000000fceb70 ***
</pre>

I cannot reproduce this crash on OSX. Please take a look, thank you!

**Comment by JanWielemaker** [comment]
`valgrind` is your friend.    The blob handling was incorrect.  You basically want to use the pointer as your blob.  I think it is fixed now.  The crash didn't reproduce on Ubuntu, but valgrind was quite noisy about invalid memory access.

**Comment by triska** [comment]
I do *not* consider this issue fixed: I still get the exact same crash even after applying your patch.

**Comment by triska** [comment]
Also, if this blob handling is incorrect, then so is that of `ssl4pl.c`, please have a look. Thank&nbsp;you!

**Comment by JanWielemaker** [comment]
That indeed looks suspicious too.   First though, what is wrong here.  Are you absolutely sure you got the latest version (3d5be96bcc78d5ee98e6e66d3a9277ea62567739) and you really recompiled it and are really running this version?  If so, try running `valgrind swipl -f none bitcoinolog.pl` and the same goal.  Valgrind is a CPU emulator, so it is slow (approx 20 times slower than native).   If anything goes wrong it complains.  If you make sure to add `-g` or better `-gdwarf-2 -g3` to the C compiler flags you should get quite detailed information about what is wrong.   To me, the blob handling look ok now.  Didn't check the allocation and free of all the parts.   The other option we have is the `-fsanitize=address` feature of gcc, but in most cases valgrind is slower but more accurate.

**Comment by JanWielemaker** [comment]
Although I'm not sure, it might be the case that despite the invalid memory access of the blob stuff, there was nothing really wrong.  That may suggest that the issue relates to the OpenSSL version.   Well, possibly `valgrind` will give a hint.

**Comment by triska** [comment]
After several compile-delete-recompile cycles of the most recent OpenSSL versions, I can also no longer reproduce the issue, even though I could previously reproduce it with 2 different recent&nbsp;versions (1.1.0c and 1.1.0f). Thank you for looking into it in any case.

In case it helps in the future, I found that the following sufficed to reproduce the crash:

<pre>
?- repeat, crypto_context_new(C, [algorithm(ripemd160)]), garbage_collect_atoms, false.
</pre>

Further, commenting out the line `EVP_MD_CTX_free(c->ctx)` in `free_crypto_context()` made the crash go away for those combinations of library versions and (apparently flawed) compilations where it&nbsp;arose.

If possible, please have a look at `ssl_context/3`, where the same blob handling is used. I ran `ssl_context/3` within valgrind, and it showed no errors at&nbsp;all.
