### ISSUE TITLE
Improved support for rational numbers

### ISSUE THREAD

**Issue by ridgeworks** [SWI-Prolog/swipl-devel#539]
Rational numbers are important in mathematics because they are precise (compared to floating point, which is not). Arithmetic operations (`+,-,*,/,**`) on precise values yield precise values. Without rationals, the only precise arithmetic is integer arithmetic.

The current implementation of rational numbers in SWI-Prolog is a halfway house which has a number of issues:

1. External to runtime arithmetic evaluation predicates, they're not numbers; they're really subexpressions that can be used to construct an internal (precise) numeric value that can be used in arithmetic operations resulting in precise values. This has two undesirable consequences: they fail the number sniff test (`number/1`) and the standard list sorting predicates, e.g., `sort/2`, which are based on standard term ordering, cannot be used to create an ascending list of numeric values.  

2. The divide operation (`/`) is inconsistent with the other arithmetic operations. While adding, subtracting or multiplying rationals result in a rational, division results in a (imprecise) float unless it is an integer. To cope with this, a separate divide operator is required to force a rational result. 
Divide is not alone in this respect; power (`**` and `^`) has similar issues in that rational and negative powers return floats when they could return a rational, e.g., `X is 4**(1 rdiv 2)`, `X is 2** -2`. (Less important but worth considering are the other arithmetic functions, e.g.,sqrt.)

3. Although arithmetic performance is usually not a critical issue in most Prolog programs, the current implementation is inefficient in that it forces a conversion to the internal format every time a rational number is used in an expression. Note that `X is 2 rdiv 3` is just a more expensive way of saying `X = 2 div 3`. 
As an example, consider the evaluation of the "Six Hump Camel Function"  when X1 and X2 are rational numbers:
`? - F is 4-(21 rdiv 10)*X1**2+(1 rdiv 3)*X1**4)*X1**2+X1*X2+(4*X2**2-4)*X2**2.`
There are only two "variables" but nine internal conversions (including the two "constants").

4. Unlike integers and floats, and unlike rational numbers supported in other programming languages (e.g., Common List, Python, Ruby, Wolfram) there is no native Prolog format for rational literals. This not only affects usability but means that the conversions discussed in 3. cannot be done at compile/parse time, further impacting performance.

To address these issues, I propose the following:

1. Promote the internal rational representation so it appears outside arithmetic evaluation. If `X` is unified with a rational number, the filters (see reference 4.6)  `rational(X), number(X), atomic(X), ground(X), acrylic_term(X), nonvar(X)` should all succeed; all others should fail. If `integer(X)` then `rational(X)`. 

2. Since rationals are now numbers (and integers are rationals, the "Standard Order of Terms" (Ref. 4.7.1) should be:
"_Numbers_ are compared by value. Mixed rational/float are compared as floats (`integer(X)` implies `rational(X)`). If the comparison is equal, the float is considered the smaller value. If the Prolog flag `iso` is defined, all floating point numbers precede all rationals."

3. The divide (`/`) and power (`**,^`) operations should be fixed to be consistent with the add, subtract and multiply (`+,-,*`), i.e., if a precise representation can be calculated, it should be returned rather than a float. (This is not ISO compatible, but ISO doesn't have rationals in any case.)

4. A rational literal syntax following the Ruby convention, e.g., `1/2r`, should be introduced. The use of a letter is consistent with other number literal formats, e.g., `0b101, 0o77, 0xfe, 1e3`. The rational literal syntax is used for outputting rational terms as well as input.

5. Deprecate `rdiv`. I think it can co-exist with the added benefit that `X is 2 rdiv 3` will actually do something useful.

**Comment by esad** [comment]
For practical usage, it would also be nice to include a predicate for converting from strings and support strings in rationalize/1. While `format` can be used to output rationals, it would be also nice to have a dedicated predicate for output to string, or maybe a single predicate can handle both conversions.

**Comment by ridgeworks** [comment]
If this was implemented, I would assume any SWIP core predicates dealing with numbers would be required to support rationals, including `number_string/2` (and similar string predicates). Does this address your concern?

**Comment by esad** [comment]
@ridgeworks: I am not sure `number_string/2` allows specifying what kind of number one wants (rational, float, int) etc. How would I make `number_string(N, "0.0001")` use rational representation instead of floats?

**Comment by ridgeworks** [comment]
@esad 
I would assume it would work the same way it does now with integers and floats:
```
?- number_string(N,"1.0").
N = 1.0.

?- number_string(N,"1").
N = 1.
```
Once rationals are true numbers and have a native syntax, you would use that, e.g.,
`?- number_string(N,"1/2r").`

**Comment by esad** [comment]
I don't think integer/float is a good counter example - while it's safe to convert a string that represents an integer to an integer (itself a subset of rational), converting a string that has a decimal separator can be done either to float or to rational, former with loss of precision (see example below), so user may want to supply what number representation they want.

`number_string(N, "0.00000001"), X is rationalize(N), X = 1 rdiv 99999999.`

**Comment by esad** [comment]
Having to rely on an explicit "r" string suffix is not so ergonomic, esp. when parsing external data - in which case one would have to preprocess all number-strings and append "r" to them. For example in json, one would encode currency amounts as strings (`"123.45"`) to avoid loss of precision when encoding as float, so it wouldn't even be so easy to solve this by supplying an option to the json parser as it can't differentiate "numbers as strings" from regular strings.

**Comment by ridgeworks** [comment]
No, in a language syntax context, ambiguity shouldn't be allowed. So a numeric string with a decimal point should not either a float or rational.  (By analogy, the string "1" is an integer, not an integer or a float.) To my knowledge all programming languages interpret such a string as a float. So `number_string` (or `term_string`) which parses a string in Prolog syntax does not (and should not) do what you want. 

If you want to use a different (non-native) syntax for a rational then a custom parser (like the one you've written) is needed. 

An alternative: the current floating point syntax could be universally converted to a rational, not a IEEE binary. (All IEEE floats can be precisely expressed as rational numbers.) I suspect this would be rejected for efficiency (time and space) reasons.

I think the underlying reason you want this is that float conversion and arithmetic is imprecise, so you're trying to use precise rationals internally and float syntax externally. (As a matter of interest, how would implement this using a programming language that didn't support rational numbers? Would you just live with floating point or would you invent a new number "class"?) 


Aside: it would be nice to use `p/q` syntax for rationals like most other languages with rational number support, but that would get parsed by Prolog as `/(p,q)`, hence the `r` suffix (like Ruby).

**Comment by JanWielemaker** [comment]
See also comments by Joachim Schimpf for ECLiPSe at http://eclipseclp.org/wiki/Prolog/Rationals

**Comment by JanWielemaker** [comment]
Copied the following from a mail from Joachim.  If/when we do proper rationals I want that compatible with ECLiPSe if we can reach an agreement.  In the past we managed to get to agreements and this doesn't look too hard.

> The poster suggests 1/3r or 1/3R.  The latter is of course fully
> unambigous. 

I think that's a very bad idea.  You want to recognize a rational
in the lexer, but with this syntax you have to parse 3 potential
tokens until you can decide whether it is a single rational token
or a sequence of integer,atom,integer tokens.

Moreover, it would be natural to allow 3R as a shorthand for 3/1R,
in which case you get an ambiguity between parsing 3/1R as a
single rational or as compound /(3,1R).


>  Following your list, 1R3 would, I guess, also work.

Being a visual person, I kind of like the look of 1_/3, as it reminds
me of both a horizontal fraction bar and the division slash.

But I suppose 1R3 looks more mainstream and acceptable!

**Comment by ridgeworks** [comment]
I'm not strongly opinionated on the syntax for rational number literals. Compatibility with Eclipse is something I hadn't considered and certainly higher priority than compitibilty with, e.g. Ruby.

But,
> I think that's a very bad idea. You want to recognize a rational
> in the lexer, but with this syntax you have to parse 3 potential
> tokens until you can decide whether it is a single rational token
> or a sequence of integer,atom,integer tokens.
> 
I don't find this is a very compelling argument. IMO the syntax should visually express the semantics, and if that complicates the parsing a bit, you should pay the price.  (Don't the other literal number formats, e.g., `-1.23e-02` and `-0x8c` have similar issues?)

> Moreover, it would be natural to allow 3R as a shorthand for 3/1R,
> in which case you get an ambiguity between parsing 3/1R as a
> single rational or as compound /(3,1R).
> 
I don't see this as natural or why a shorthand is even useful. Why would someone think it's better to write `3R` as opposed to `3`. The noted ambiguity would be another reason to not support this.  (In SWI-Prolog `3/1R` would be reduced to an integer in any case.)

I'm also a visual person so `1/3r` would still be my first choice (given that the commonly used `1/3` is a non-starter). I suggested `1/3R` as an alternative because the floating point syntax permits either `e` or `E` but i note that the integer radix letters  are all lowercase so that argument is weak. Given that, maybe `1/3_` might be even better than using a letter and it certainly doesn't make sense to define `_` as an operator.

However, If Eclipse compatibility is more desirable than an expressive syntax then it should be fully compatible, i.e., just use the `_` notation. Half compromises like `1_/3` don't seem to be worth it. 

I fully support the "Computations" section of the Eclipse paper, and it should replace item 3. in my original proposal.

**Comment by ridgeworks** [comment]
Implementation Notes - #1 Storage format (TAGS)

My take after poking around the source in case they're useful to anyone taking this further.

It would probably be preferable if rational numbers had a unique tag like `TAG_INTEGER` and `TAG_FLOAT` (`pl-data.h`). However there are no unused values within the current 3 bit range.

The next best option is to use the the extended storage tag bits (`STG_MASK`). These are currently used to distinguish between inline integers and extended integers in global storage. `TAG-INTEGER` is only used with two of these values, so one of the other values (e.g., `STG_RESERVED`)  is a possibility. However this may conflict with other uses of these 2 bits.

If neither of the above is feasible (or desirable), use the same tag format as that used for extended integers i.e., `TAG_INTEGER | STG_GLOBAL` and use the size of data structure allocated on the global stack to distinguish rational numbers from other indirect `TAG_INTEGER` formats. On a 64 bit system:

`sizeof(Bignum) = sizeof(int64_t)       (8 bytes/sizeof(word))`
`sizeof(MPZNum) = sizeof(__mpz_struct)  (2+2+8=10 bytes in a 64 bit system)`
`sizeof(MPQNum) = sizeof(__mpq_struct)  (2 * sizeof(MPZNum))`

Assuming last scheme (no changes to term level tags), changes to `pl_data.h`:

```
- fix:	#define isInteger(w)	(isTaggedInt(w) || isBignum(w) || isMPZNum(w))
- add:	#define isRational(w)	(tag(w)   == TAG_INTEGER)`
- fix: 	#define isMPZNum(w)	(tagex(w) == (TAG_INTEGER | STG_GLOBAL) && \
			 wsizeofIndirect(w) == sizeof(__mpz_struct)/sizeof(word))
- add:	#define isMPQNum(w)	(tagex(w) == (TAG_INTEGER | STG_GLOBAL) && \
			 wsizeofIndirect(w) == sizeof(__mpq_struct)/sizeof(word))
- fix:	#define isNumber(w)	(isRational(w) || isFloat(w))
```
In addition the following doesn't look right (support for MPZ integers?):
```
- fix?:	#define valInteger(w)	(storage(w) == STG_INLINE ? valInt(w) : valBignum(w))
```
Note: the above assumes the that `__mpz_struct` and `__mpq_struct` defined in `gmp.h`  are visible when compiling pl_data which I don't think is currently the case and I don't know enough about the "big picture" to suggest a good solution. Moving the definitions of `isMPZNum` and `isMPQNum` to `pl_gmp` might help except that the above definition of `isInteger` is dependent on  `isMPZNum`.

The affected functions responsible  for moving numeric values to/from Prolog terms to instances of `Number` appear to be mainly in `pl_gmp.c`. A quick scan suggests the following need attention:

`get_integer` - can't assume all `TAG_INTEGER | STG_GLOBAL` are integers
`get_number, PL_get_number__LD` - need to handle numeric rationals
`put_number` - should construct a numeric rational rather than `rdiv` compound term

 Others:
`pl_arith.c` : `valueExpression` - need to handle numeric rationals (currently uses `get_integer`)
`pl_write.c` : `writeNumberVar, writeNumber` - need to handle numeric rationals 

This may not be a complete list and additionally doesn't cover support for rational literals or expression evaluation issues.

**Comment by triska** [comment]
Regarding this statement:

> Given that, maybe 1/3_ might be even better than using a letter 

Please note that `_` is necessary to write **integers** across several lines, for example like this:

<pre>
?- X = <b>123_
|    456</b>.
</pre>

yielding:

<pre>
X = <b>123456</b>.
</pre>

On a single line, it could be written as `123 456` (i.e., with a space), but the space cannot be used at the end of the line, so `_` must be used instead!

Hence, we have already now:

<pre>
?- X = <b>1/3_
|    4.</b>
<b>X = 1/34</b>.

**Comment by ridgeworks** [comment]
I did not know that. Seems a bit bizarre and only works with decimal integers (not radix integers, e.g., `0xff`). In addition, `_`, as well as a single space character and the singular case of an underscore followed by a space, is allowed internal to (decimal) integers, so it's not just a line continuation issue.
```
?- number_string(N,"123_45").
N = 12345.

?- number_string(N,"123 45").
N = 12345.

?- number_string(N,"123_ 45").
N = 12345.

?- number_string(N,"123  45").
false.

?- number_string(N,"123__45").
false.

?- number_string(N,"123 _45").
false.
```
 
So the first point is this would seem to preclude using the Eclipse syntax for rational numbers.

The second point is that if the decimal integer syntax can include `_` and ` ` then any rational number syntax should probably do the same. 

So I'm to back `1/3r`, as well as `1 2/4_`
`5r`. And how about `0b101/0xfcr`?

**Comment by triska** [comment]
To clarify: You are right, it's of course not just a line continuation issue!

I mentioned this to show that we cannot simply use space instead of `_` in all cases. The example I posted shows that this is not possible: We truly need the `_` syntax because this is the only way to make an integer span multiple lines.

**Comment by ridgeworks** [comment]
So perhaps the proposed rational literal syntax should be specified as "<integer>/<integer>r"  where <integer> is the currently supported syntax for integers.

**Comment by JanWielemaker** [comment]
Does anyone know about an overview of existing rational number notations, basically in general, but in particular for programming languages?

**Comment by JanWielemaker** [comment]
> - fix: 	#define isMPZNum(w)	(tagex(w) == (TAG_INTEGER | STG_GLOBAL) && \
> 			 wsizeofIndirect(w) == sizeof(__mpz_struct)/sizeof(word))
> - add:	#define isMPQNum(w)	(tagex(w) == (TAG_INTEGER | STG_GLOBAL) && \
> 			 wsizeofIndirect(w) == sizeof(__mpq_struct)/sizeof(word))

That won't really work.  An MPZ number doesn't just contain the header, but also the actual bits and thus the size is larger than just the header.   We should do the same for MPQ and use the tag bits on the indirect header to distinguish between MPZ and MPQ.   This is not too bad.  wsizeofIndirect must also look at the global stack data.   As 99% of the integers that matter for speed are typically inline integers the performance impact is probably not a real problem either.

**Comment by ridgeworks** [comment]
@JanWielemaker 

Just to capture what I discovered in my earlier search for the discussion topic (`P` and `Q` are integers):

`P/Q` : Common Lisp, Python (fractions), OWL, Guile, Wolfram
`P//Q` : Julia (also allows Q to be signed)
`P/Qr` : Ruby

Also this (I probably should have seen it sooner):
[Rational_data_type](https://en.wikipedia.org/wiki/Rational_data_type)

Not very many languages have a native syntax.

**Comment by ridgeworks** [comment]
> That won't really work. An MPZ number doesn't just contain the header, but also the actual bits and thus the size is larger than just the header. We should do the same for MPQ and use the tag bits on the indirect header to distinguish between MPZ and MPQ. This is not too bad. wsizeofIndirect must also look at the global stack data. As 99% of the integers that matter for speed are typically inline integers the performance impact is probably not a real problem either.

I was using the current `isBigNum`/`isMPZNum` as a model; they use the different sizes as a distinguishing characteristic. I think you're saying that the included numeric data means the sizes are variable so it's possible that a (very large) MPZ could be the same size as a (smallish) MPQ.

In any case, if there are tag bits on the indirect pointer they should be used. I just didn't see where they are defined.

**Comment by JanWielemaker** [comment]
> I think you're saying that the included numeric data means the sizes are variable so it's possible that a (very large) MPZ could be the same size as a (smallish) MPQ.

Yes.  This only works for a 64-bit `Bignum` vs MPZ as MPZ is only used if the integer doesn't fit in 64-bit and (thus) the MPZ is always greater than 64-bit.

But, you correctly observe there is no tag bit on indirect headers.   They existed only in my head :cry:.  If we look at globalMPZ() and get_integer(), we see that the stack serialization contains first a word holding the MPZ size, followed by the MPZ bits.   As we cannot support the full 32-bit MPZ numbers (they do not fit on the stack), we can easily shift the size and use the least significant bit to store MPZ vs MPQ.  In other words, you get

  - size<<1, bits for MPZ
  - size nominator<<1|0x1, size denominator, nominator bits, denominator bits for MPQ

**Comment by JanWielemaker** [comment]
> `P/Q` : Common Lisp, Python (fractions), OWL, Guile, Wolfram

I'll probably make some enemies, but what really goes wrong if <integer>/<integer> produces an MPQ number?  After all, `-42` also produces an integer rather than a term -(42).   In ISO it is even demanded that ``-  /*hello*/ 42`` produces an integer rather than a term (SWI-Prolog demands no space between the `-` an the first digit).

After all, used in arithmetic, it doesn't matter.  Only if the user wants a _term_ it does and like writing -(42), the user must write /(42,21) or (42)/21 or 42/(21) or, in SWI-Prolog following `-`, ``42 / 21``.  I tried a grep for '[0-9]/[0-9]' on a lot of Prolog code.  Unfortunately that gives a lot of hits on dates in comments but I would be rather surprised if there is a real hit.

Also note that code is quickly checked for this.  Just analyze the code for MPQ numbers appearing in the clauses.  That is pretty much what the checker for the ``"string"`` notation also does, but this is far less likely to trigger and if there is a hit it is far less likely to be a false positive.   If it proves to be problematic we could still have a flag.

**Comment by ridgeworks** [comment]
@JanWielemaker 
> If we look at globalMPZ() and get_integer(), we see that the stack serialization contains first a word holding the MPZ size, followed by the MPZ bits. As we cannot support the full 32-bit MPZ numbers (they do not fit on the stack), we can easily shift the size and use the least significant bit to store MPZ vs MPQ.

At one point I had a similar thought: negate the size for MPQ's. But whatever works; I'm a bit out of my depth here to say the least.

**Comment by triska** [comment]
>  if / produces an MPQ number? 

That's a logical solution.

Please note that the ISO standard makes no demands whatsoever about how you *internally* represent your terms. It is perfectly admissible to represent, internally, 1/2 as a GMP&nbsp;blob. However, all the built-in predicates like `functor/3` etc. should still work correctly.

So, for example, we would still get:

<pre>
?- X = 1/2, functor(X, F, A).
<b>A = 2, F = /, X = 1/2.</b>
</pre>

no matter how `X` is internally represented.

This is the exact same situation for strings: A Prolog system can internally represent `"abc"` very efficiently, say as a buffer of raw bytes. And externally, i.e., to Prolog predicates such as `(=)/2`, treat it as a list of characters, and display it as `[a,b,c]` on the toplevel. Like for rationals, this only necessitates the modification of built-in predicates to treat the internal data accordingly, so that all properties we expect are preserved.

**Comment by ridgeworks** [comment]
> I'll probably make some enemies, but what really goes wrong if / produces an MPQ number?

Well I like this solution, but I wondered if it would fly. As you say, there are workarounds but it's not strictly backward compatible. But it's not the only compatibility issue if the division and power operators start producing rationals as proposed (also Eclipse paper).

Apart from the term vs. number issue you raised, I guess there might be some objection based on efficiency (`1/2` currently evaluates to a float). The solution is simple, just use floating point constants.

@triska writes:

So, for example, we would still get:
```
?- X = 1/2, functor(X, F, A).
A = 2, F = /, X = 1/2.
no matter how X is internally represented.
```
This I'm not so sure about. How would the filters behave, e.g., `compound(1/2)`, `number(1/2)`, `atomic(1/2)`. And if a rational is `atomic`, shouldn't it have an arity of 0 like all the other atomics?  (SWIP strings are `atomic`.)

As a general matter of principle, I like to see transparency between the implementation and presentation; it just helps keep my mental model straight.

**Comment by JanWielemaker** [comment]
> but it's not strictly backward compatible

True.  As far as I'm concerned you have to balance between compatibility and usability.  You either go for rationals as some sort of secondary citizen or you turn them into primary citizens as they should have been since the beginning of Prolog.  If you do the latter, some things will break.  My intuition is though that this will be pretty minor.

> @triska: X = 1/2, functor(X, F, A).
> @ridgeworks: I'm not so sure about

I don't think this is a particularly good idea either.   If we go for 1/2 is a rational, it will be atomic and functor will do what it does on other atomic types.   That is no different from `-42`.   

Some details do need settling.  What about `1/2.0`?  It clearly cannot be a rational as we do not want fuzzy floats to become precise rationals.  That leaves two options:  a term /(1,2.0) or, in SWI-Prolog's spirit using '.' as an operator a term `.(1/2, 0)`.  This tuns e.g. `1/2e10` into a syntax error.  Form a compatibility point of view creating /(1/2.0) and /(1,2e10) is probably best, but from an syntactic clarity point of view I think it should be a syntax error.

**Comment by ridgeworks** [comment]
> You either go for rationals as some sort of secondary citizen or you turn them into primary citizens as they should have been since the beginning of Prolog.

i.e., what this issue is all about. Clearly my vote is for primary citizenship.

> Some details do need settling.

It doesn't seem possible to move without hitting something. For example `.` as a functor seems to get entangled with dictionaries:
```
?- X= .(1,2).
ERROR: Type error: `dict' expected, found `1' (an integer)
ERROR: In:
ERROR:   [13] throw(error(type_error(dict,1),_12164))
ERROR:   [10] '<meta-call>'(user:(...,...)) <foreign>
ERROR:    [9] <user>
ERROR: 

?- X= a.b.
ERROR: Type error: `dict' expected, found `a' (an atom)
ERROR: In:
ERROR:   [13] throw(error(type_error(dict,a),_13452))
ERROR:   [10] '<meta-call>'(user:(...,...)) <foreign>
ERROR:    [9] <user>
ERROR: 
```
Note that they parsed fine, but the dict code seems to be activated in a way I didn't expect. Also note that the `.` operator has a very low precedence (100) so `1/2.0` would not naturally be parsed as as a `.` term, would it? 

Anyway `1/2.0` definitely shouldn't be a rational. `/(1,2.0)` makes the most sense to me and seems consistent with operator precedence.

**Comment by JanWielemaker** [comment]
> Anyway `1/2.0` definitely shouldn't be a rational. `/(1,2.0)` makes the most sense to me and seems consistent with operator precedence.

Possibly, but if we use this in an arithmetic context this will pass on as 0.5, introducing floats which we didn't want ...   Also related is whether we should or should not allow for white space around `/`.  Just tested ECLiPSe and we get a syntax error for `A = 1 _ 2`.  This makes sense, but on the other hand it would be very natural to use a line break before/around/after the separator.  SWI-Prolog would allow for

```
42/2
1
```

But 

```
42/
21
```

makes a lot more sense to me.   If we allow for white space, the change to the reader could merely be to reduce /(int,int) to a rational rather than a term, but this smells fishy to me.  Atomic values should be handled as tokens or we get ambiguous results depending on the active operators.

**Comment by ridgeworks** [comment]
> Possibly, but if we use this in an arithmetic context this will pass on as 0.5, introducing floats which we didn't want ...

With current operator precedence, possible options for `1/2.0` 
1. `/(1,2.0)`
2. `.(1/2,0)`
3. `/(1,.(2,0))`

IMO, there are some issues with `.` as an operator. First, I can't just use it as an infix operator, or as a functor, as demonstrated in my previous email. To actually construct such a term, I can use `=..`:
```
?- X =.. [.,a,b].
X = a.b.
```
But also:
```
?- X=..[.,1,0],\+float(X).
X = 1.0.
```
so X looks like a float but isn't one. 

Given all this, I would not further legitimize interpreting `.` as an operator. Which leaves me with option 1. And that means `1/2.0` would evaluate to a float. (As would `1*2.0`.) I think this is fairly intuitive. Presumably things like `1/2.e` will continue to generate errors.

Regarding whitespace and line breaks: I think integers are the only atomic terms (maybe strings?) that can be broken over lines (using `_` as previously discussed). So that should probably be carried over to integers which are the components of rationals. When used in a rational, I tend to think of `/` as part of the native syntax like the `.` or `e` in a float literal. Or the `b` in an integer. This is in line with your view of atomic values as tokens. So whitespace and linebreaks would not be permitted around the `/` in a rational; it's not an operator, it's part of the rational syntax, just like `.` in a float is not an operator. 

This does permit an easy alternative to using `/` as a operator :`1 / 2` is a compound term, `1/2` is a rational. It may seem a bit odd at first, but `2.0` is clearly different from `2 . 0`.

**Comment by JanWielemaker** [comment]
Thanks.  I'll continue this on Discourse as that is more widely read and better suited for discussion.  In the meanwhile, I've pushed a branch `rational` that provides a first prototype.  See Discourse for further announcement.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/proper-rational-numbers-prototype-for-testing/1810/1

**Comment by jburse** [comment]
This flag doesn’t solve a certain problem cause by the fact
that for example 2r1 = 2 now in SWI-Prolog:

    set_prolog_flag(prefer_rationals, true)

In ECLiPSe Prolog 2_1 \= 2. So in ECLiPSe Prolog I have 
rationals and floats side by side:

```
ECLiPSe Version 7.0 #52 (x86_64_nt)

[eclipse 1]: X is 2_1^(-5).
X = 1_32
Yes (0.00s cpu)

[eclipse 2]: X is 2^(-5).
X = 0.03125
Yes (0.00s cpu) 
```

With the SWI-Prolog flag I still dont get float and rational side by side:

```
SWI-Prolog (threaded, 64 bits, version 8.1.22)

?- set_prolog_flag(prefer_rationals, true).
true.

?- X is 2^(-5).
X = 1r32.

?- X is 2**(-5).
X = 1r32.
```

The flag also affects (**)/2. How can I have something inbetween 
prefer_rationals=true and prefer_rationals=false?

**Comment by JanWielemaker** [comment]
`X is 2.0^(-5)` or `X is 2^(-5.0)` or `X is float(2)^(-5)`, etc.   We don't have different `/`, `*`, etc. either.  ISO somewhere decided two have two exponentiation functions, which IMO was a rather odd choice I have advised against at the time, but lost.

The deal should be "you get the most precise answer" except for a few pure real number functions that happen to have a couple of values in Q.   It is not unlikely that `prefer_rationals` will in the future be `true` by default.   If you want a less precise answer (typically read: a float), make sure one of the operands is float.

**Comment by jburse** [comment]
You will need all the float operations for interval arithmetic. How
do you retain something like:

    ?- current_prolog_flag(float_rounding, Safe),
        set_prolog_flag(float_rounding, Mode),
        X is Y**Z,
        set_prolog_flag(float_rounding, Safe).

Chaing the the prefer_rationals flag as well each time?

**Comment by JanWielemaker** [comment]
This is all dealt with AFAIK.  Closing.
