### ISSUE TITLE
terms:same_functor handling of atomic terms/arity 0 is incompatible with SICStus

### ISSUE THREAD

**Issue by dgelessus** [SWI-Prolog/swipl-devel#815]
SWI's `same_functor` is implemented using `compound_name_arity/3`, meaning that it throws an error if either term is atomic, and interprets arity 0 as a no-arg compound term rather than an atom. This is incompatible with the SICStus behavior, where `same_functor` works like `functor/3`, i. e. treating atomic terms as having arity 0 (and no-arg compound terms don't exist in SICStus).

For example, all of the following calls succeed or fail without error on SICStus:

```prolog
| ?- same_functor(some_atom, some_atom).
yes
| ?- same_functor(some_atom, some_atom, Name, Arity).
Name = some_atom,
Arity = 0 ? 
yes
| ?- same_functor(some_atom, some_functor(arg), Name, Arity).
no
| ?- same_functor(A, B, some_atom, 0).
A = some_atom,
B = some_atom ? 
yes
| ?- same_functor(123, some_atom).
no
| ?- same_functor(A, B, 123, 0).
A = 123,
B = 123 ? 
yes
| ?- same_functor(A, B, 123, 5).
no
```

But on SWI, they all currently throw a type error, because of `compound_name_arity/3`'s stricter requirements.

The easy fix for SICStus compatibility would be to implement `same_functor` using `functor/3` instead of `compound_name_arity/3`. But I don't know if this behavior is desirable in general for SWI. For example, `mapargs/3` uses `same_functor` in its implementation, and in that case it makes sense to throw an error for anything that isn't a real compound term.

**Comment by JanWielemaker** [comment]
I pushed 89c08b9f81e9abf7002ab8e581b18a414ef739a4.  Does this address the issue good enough?

**Comment by dgelessus** [comment]
Thanks, `same_functor` now works as expected when both terms are atoms. Unfortunately it still throws an error if one term is an atom and the other is a compound:

```prolog
?- same_functor(A, B, foo, 0).
A = B, B = foo.
?- same_functor(foo, foo, Name, Arity).
Name = foo,
Arity = 0.
?- same_functor(foo, bar, Name, Arity).
false.
?- same_functor(foo, bar(a, b, c), Name, Arity).
ERROR: Type error: `compound' expected, found `foo' (an atom)
ERROR: In:
ERROR:   [11] compound_name_arity(foo,bar,3)
ERROR:    [9] toplevel_call(user:user: ...) at <builddir>/home/boot/toplevel.pl:1113
```

I should have probably given more context in my original post... The code where I'm running into this problem compares two ASTs, and as a first step it always checks `same_functor(Expr1, Expr2)`, where `Expr1` and `Expr2` (both nonvar) can be either atoms or compound terms. The expectation is that `same_functor` will silently fail if `Expr1` and `Expr2` are not matching atoms or compound terms.

Our code only uses the mode `same_functor(+Term1, +Term2)` as far as I can tell, so the exact behavior for other arities/modes is less important to me.

**Comment by JanWielemaker** [comment]
Thanks for the explanation.   This required some though.   I think I found an elegant solution by introducing functor/4 and implement same_functor based on that.

**Comment by dgelessus** [comment]
Yep, the new `same_functor` implementation seems to handle everything as expected now. Thanks again for the help!
